apiVersion: v1
kind: Service
metadata:
  name: debezium-connect-service
  namespace: cdc
spec:
  type: LoadBalancer
  selector:
    app: connect
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083